// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUnFAgBpMr3vtCe7EJ_T5W_XIwrPNfgU0',
    appId: '1:399843481414:web:95f2ce9b08ca8d34803747',
    messagingSenderId: '399843481414',
    projectId: 'fashion-store-app-409bf',
    authDomain: 'fashion-store-app-409bf.firebaseapp.com',
    storageBucket: 'fashion-store-app-409bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjzAxg8xA8kFmRnDsWHTdJwYmjy-JOKVY',
    appId: '1:399843481414:android:0403003b18f43ade803747',
    messagingSenderId: '399843481414',
    projectId: 'fashion-store-app-409bf',
    storageBucket: 'fashion-store-app-409bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1prShM2MnOn2eZeCTqUdwr6h3cEMc62k',
    appId: '1:399843481414:ios:95bbe4da96996c0f803747',
    messagingSenderId: '399843481414',
    projectId: 'fashion-store-app-409bf',
    storageBucket: 'fashion-store-app-409bf.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1prShM2MnOn2eZeCTqUdwr6h3cEMc62k',
    appId: '1:399843481414:ios:95bbe4da96996c0f803747',
    messagingSenderId: '399843481414',
    projectId: 'fashion-store-app-409bf',
    storageBucket: 'fashion-store-app-409bf.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUnFAgBpMr3vtCe7EJ_T5W_XIwrPNfgU0',
    appId: '1:399843481414:web:6180bc4c64faeea7803747',
    messagingSenderId: '399843481414',
    projectId: 'fashion-store-app-409bf',
    authDomain: 'fashion-store-app-409bf.firebaseapp.com',
    storageBucket: 'fashion-store-app-409bf.firebasestorage.app',
  );
}
